# Generated by Django 3.1.2 on 2020-11-08 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submittext', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chattext',
            name='time',
            field=models.DateTimeField(default='2020-11-08 14:19:23.427852'),
        ),
    ]
