# Generated by Django 3.1.2 on 2020-11-08 10:52

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('submittext', '0002_chattext_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chattext',
            name='parent_text',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='submittext.chattext'),
        ),
        migrations.AlterField(
            model_name='chattext',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 8, 14, 22, 3, 56083)),
        ),
    ]
