# Generated by Django 3.1.2 on 2020-11-08 10:53

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('submittext', '0003_auto_20201108_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chattext',
            name='parent_text',
            field=models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='submittext.chattext'),
        ),
        migrations.AlterField(
            model_name='chattext',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 8, 14, 23, 2, 689036)),
        ),
    ]
