# Generated by Django 3.1.2 on 2020-11-13 04:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submittext', '0004_auto_20201113_0735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chattext',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 13, 7, 47, 28, 242097)),
        ),
    ]
