# Generated by Django 3.1.2 on 2020-11-13 05:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submittext', '0005_auto_20201113_0747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chattext',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 13, 8, 46, 15, 382676)),
        ),
    ]
