# Generated by Django 3.1.2 on 2020-11-12 15:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submittext', '0005_auto_20201108_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chattext',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 12, 19, 13, 27, 188091)),
        ),
    ]
