# Generated by Django 3.1.2 on 2020-11-13 07:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submittext', '0006_auto_20201113_0846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chattext',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 13, 11, 11, 21, 953911)),
        ),
    ]
