# Generated by Django 3.1.2 on 2020-11-13 07:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submittext', '0008_auto_20201113_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chattext',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 13, 11, 13, 59, 469196)),
        ),
    ]
