# Generated by Django 3.1.2 on 2020-11-13 18:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submittext', '0011_auto_20201113_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chattext',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 13, 22, 13, 33, 279659)),
        ),
    ]
