# Generated by Django 3.1.2 on 2020-11-13 19:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submittext', '0013_auto_20201113_2238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chattext',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 13, 22, 45, 17, 32622)),
        ),
    ]
