# Generated by Django 3.1.2 on 2020-11-14 15:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submittext', '0018_auto_20201114_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chattext',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 14, 15, 31, 3, 254247)),
        ),
    ]
