# Generated by Django 3.1.2 on 2020-11-14 15:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submittext', '0020_auto_20201114_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chattext',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 14, 15, 34, 9, 211093)),
        ),
    ]
