# Generated by Django 3.1.2 on 2020-11-14 17:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submittext', '0024_auto_20201114_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chattext',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 14, 17, 58, 20, 698773)),
        ),
    ]
