# Generated by Django 3.1.2 on 2020-11-15 06:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submittext', '0028_auto_20201114_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chattext',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 15, 10, 21, 41, 407955)),
        ),
    ]
