# Generated by Django 3.1.2 on 2020-11-15 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submittext', '0029_auto_20201115_1021'),
        ('submittext', '0029_auto_20201114_2039'),
    ]

    operations = [
    ]
