# Generated by Django 3.1.2 on 2020-11-15 08:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submittext', '0030_merge_20201115_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chattext',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 15, 12, 25, 43, 930797)),
        ),
    ]
