# Generated by Django 3.1.2 on 2020-11-15 07:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submittext', '0031_auto_20201115_0750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chattext',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 15, 7, 53, 27, 26192)),
        ),
    ]
