# Generated by Django 3.1.2 on 2020-11-15 08:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submittext', '0032_auto_20201115_0753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chattext',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 15, 8, 5, 1, 444895)),
        ),
    ]
