# Generated by Django 3.1.2 on 2020-11-15 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submittext', '0033_auto_20201115_0805'),
        ('submittext', '0032_auto_20201115_1650'),
    ]

    operations = [
    ]
