# Generated by Django 3.1.2 on 2020-11-20 17:26

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('submittext', '0036_auto_20201120_1923'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='file',
            field=models.FileField(null=True, upload_to='answer/file'),
        ),
        migrations.AddField(
            model_name='answer',
            name='isAccepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='answer',
            name='like',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='submittext.question'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 20, 20, 56, 15, 197866)),
        ),
        migrations.AlterField(
            model_name='answer',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='question',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 20, 20, 56, 15, 195868)),
        ),
    ]
