# Generated by Django 3.1.2 on 2020-11-20 17:43

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('submittext', '0037_auto_20201120_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='parent_text',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='submittext.answer'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 20, 21, 13, 37, 82311)),
        ),
        migrations.AlterField(
            model_name='question',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 20, 21, 13, 37, 81293)),
        ),
    ]
