# Generated by Django 3.1.2 on 2020-11-20 18:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submittext', '0039_auto_20201120_2119'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='like',
            new_name='negativeVote',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='parent_text',
        ),
        migrations.AddField(
            model_name='answer',
            name='positiveVote',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='answer',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 20, 21, 52, 34, 678865)),
        ),
        migrations.AlterField(
            model_name='question',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 20, 21, 52, 34, 678865)),
        ),
    ]
