# Generated by Django 3.1.2 on 2020-11-23 09:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submittext', '0045_auto_20201121_1952'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='positiveVote',
            new_name='vote',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='negativeVote',
        ),
        migrations.AlterField(
            model_name='answer',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 23, 12, 34, 48, 341538)),
        ),
        migrations.AlterField(
            model_name='question',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 23, 12, 34, 48, 340538)),
        ),
    ]
