# Generated by Django 3.1.2 on 2020-11-25 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submittext', '0052_auto_20201125_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='question',
            name='time',
            field=models.DateTimeField(),
        ),
    ]
