# Generated by Django 3.1.2 on 2020-12-10 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submittext', '0054_user_answer_user_question'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='commonQuestion',
            new_name='vote',
        ),
    ]
