# Generated by Django 3.1.2 on 2020-12-10 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submittext', '0054_user_answer_user_question'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_answer',
            old_name='isVoted',
            new_name='voteState',
        ),
    ]
