# Generated by Django 3.1.2 on 2020-12-10 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submittext', '0054_user_answer_user_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_question',
            name='voteState',
            field=models.IntegerField(default=0),
        ),
    ]
