# Generated by Django 3.1.2 on 2020-12-10 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submittext', '0055_user_question_votestate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='commonQuestion',
            new_name='vote',
        ),
    ]
