# Generated by Django 3.1.3 on 2020-11-21 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_comment', '0003_auto_20201121_1722'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='link',
        ),
    ]
