# Generated by Django 3.1.2 on 2020-11-12 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registeration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='askedQuestions',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='description',
            field=models.TextField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='fileField',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='user',
            name='first_name',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='user',
            name='repliedQuestions',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='', max_length=30, unique=True),
        ),
    ]
