# Generated by Django 3.1.2 on 2020-11-13 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registeration', '0003_auto_20201113_0846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
