# Generated by Django 3.1.2 on 2020-11-12 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registeration', '0005_auto_20201112_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default=models.EmailField(max_length=255, unique=True, verbose_name='email address'), max_length=30),
        ),
    ]
