# Generated by Django 3.1.2 on 2020-11-13 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registeration', '0005_auto_20201113_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(null=True, upload_to='profile_image'),
        ),
    ]
