# Generated by Django 3.1.2 on 2020-11-13 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registeration', '0008_user_interests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.FileField(null=True, upload_to='profile_image'),
        ),
    ]
