# Generated by Django 3.1.2 on 2020-11-13 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registeration', '0009_auto_20201113_2238'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='fileField',
            new_name='cvfile',
        ),
    ]
