# Generated by Django 3.1.2 on 2020-11-14 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registeration', '0011_auto_20201114_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.FileField(default='profile_image/images_9kY8zsi.png', upload_to='profile_image'),
        ),
    ]
