# Generated by Django 3.1.2 on 2020-11-14 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registeration', '0012_auto_20201114_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.FileField(default='profile_image/default-profile-picture.jpg', upload_to='profile_image'),
        ),
    ]
