# Generated by Django 3.1.2 on 2020-11-15 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registeration', '0013_auto_20201114_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.FileField(default='profile_image/text.txt', upload_to='profile_image'),
        ),
    ]
