# Generated by Django 3.1.2 on 2020-11-20 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registeration', '0014_auto_20201115_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cvfile',
            field=models.FileField(null=True, upload_to='profile/cv'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.FileField(upload_to='profile/image'),
        ),
    ]
