# Generated by Django 3.1.2 on 2020-11-25 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registeration', '0015_auto_20201125_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='numberOfChatrooms',
            field=models.IntegerField(default=0),
        ),
    ]
