# Generated by Django 3.1.2 on 2020-11-21 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registeration', '0015_auto_20201120_1523'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='repliedQuestions',
            new_name='answers',
        ),
    ]
