# Generated by Django 3.1.2 on 2020-11-21 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registeration', '0016_auto_20201121_1902'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='answers',
            new_name='answeredAnswers',
        ),
    ]
