# Generated by Django 3.1.2 on 2020-12-11 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registeration', '0017_auto_20201121_1952'),
        ('registeration', '0017_auto_20201125_1934'),
    ]

    operations = [
    ]
