# Generated by Django 3.1.2 on 2020-11-23 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registeration', '0017_auto_20201121_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
