# Generated by Django 3.1.2 on 2020-12-10 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registeration', '0017_auto_20201125_1934'),
        ('registeration', '0015_auto_20201120_1523'),
    ]

    operations = [
    ]
