# Generated by Django 3.1.2 on 2020-12-12 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registeration', '0018_merge_20201210_1354'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='answeredQuestions',
        ),
        migrations.AddField(
            model_name='user',
            name='answeredQuestions',
            field=models.IntegerField(default=0),
        ),
    ]
