# Generated by Django 3.1.2 on 2020-11-14 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CreateChatroom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chatroomAvatar', models.ImageField(upload_to='images')),
                ('chatroomName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selectedTopic', models.CharField(choices=[('app', 'app'), ('os', 'os'), ('pl', 'pl')], max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Pl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selectedPl', models.CharField(choices=[], max_length=3)),
                ('plLink', models.URLField(blank=True)),
                ('plDescription', models.CharField(max_length=100)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatroom.topic')),
            ],
        ),
        migrations.CreateModel(
            name='Os',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selectedOs', models.CharField(choices=[], max_length=3)),
                ('selectedSubOs', models.CharField(choices=[], max_length=3)),
                ('osLink', models.URLField(blank=True)),
                ('osDescription', models.CharField(max_length=100)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatroom.topic')),
            ],
        ),
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appLink', models.URLField(blank=True)),
                ('appDescription', models.CharField(max_length=100)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatroom.topic')),
            ],
        ),
    ]
